### ISSUE TITLE
Combien d'années avant que ton fils ne te batte aux échecs ?

### ISSUE THREAD

**Issue by Errinan** [rlouf/ama#1]
Ton estimation en année avant que ton fils ne te batte aux échecs ? ( modèle bayésien recommandé 👀😆)

**Comment by rlouf** [comment]
Je pense que s'il s'y met serieusement ce n'est qu'une affaire de quelques annees; les enfants ont bien plus de temps que les adultes pour potasser les sujets qui les interessent. La question est de savoir s'il va s'y tenir. Je ne le pousse pas vraiment a potasser, j'ai surtout amenage l'environnement pour. J'ai installe un grand echiquier au milieu du salon (facile d'y jouer quand on s'ennuie), et j'ai range mes bouquins juste a cote (qu'il realise la richesse du jeu). On joue regulierement ensemble et je lui explique 2-3 choses.
